banner:
    location: classpath:/banner.txt
server:
    port: 8081
    hostName: localhost

spring:
    application:
        name: scim2-compliance-test-utility
        version: 1.0.0
    jackson:
        default-property-inclusion: non_null
        serialization:
            INDENT_OUTPUT: true
    mvc:
        async:
            request-timeout: 3600000
            requestTimeout: 3600000
        profiles:
            active:
                - prod
    jpa:
        generateDdl: false
        generate-ddl: false
        hibernate:
            ddlAuto: none
            ddl-auto: none
